//Declaracion de variables para la gestion de las categorias padres
export const categorias = {
    catGenero:'01GE',
    catNivEstRiesgo:'02RE',
    catNivMarginancion:'03NM',     
    catAsentamiento:'04AS',
    catClaSecSCIAN:'05CS',
    catNivRiesgoSCIAN:'06RS',
    catTipCuenBancarias:'07CB',
    catClaAvisos:'08AC',
    catMercado:'09MC',
    catExtArchivo:'10EA',
    catTipCalculo:'11TC',
    catCondPago:'12CP',
    catActivo:'13AC',
    catPasivo:'13PA',
    catResultado:'14RS',
    catOrden:'15OR',
    catArraigo:'16TA',
    catTipCompra:'17TC',
    catMediosDifusion: '18MD',
    catNivelEscolar : '19NE',
    catTipoVivienda: '20TV',
    catRegimenMatrimonial: '21RM',
    catOrigening:'22OI',
    catActividadRealiza:'23OC',
    catTipoIngreso:'24TI',
    catTipoEgreso:'25TE',
    catFinalidadCuenta:'26FC',
    catManejoCuenta:'27MC',
    catTipoServicio:'28TS',
    catVinculoAdi:'29VA',
    catTipoContrato:'30TC',
    catReferencia:'31TR',
    catParentesco:'32PR',
    catTipoTercero:'33TT',
    catTipoOperacion:'34TO',
    catBienMaterial:'33BN',
    catTipoEmpresa:'34TE',
    catEstCivil:'35EC',
    catJerarquia:'01JD',
    catRol : '40RS',
    catTamEmpresa:'41TM',
    catGiroEm:'42GE',
    catIdentificacion:'43ID',
    catAplAval:'01AP',
    catTiposFuncionarios: '53TF',
    catJuridica:'55PJ',
    catEstatusCli: '58EC',
    catMotBajaCli:'57CB',
    catComisionesCre:'62TC',
    catCalComisiones:'61CO',
    catCargoComite:'60CC',
    catTipoNotificaciones:'63TN',
    catEstusSol:'59ES',
    catCargos: '65CP',
    tipoReporte:'68TP',
    tipoRiesgo: '69TR',
    catInstrucciones: '65II', //Tipo de instrucciones al vencimiento de Inversiones
    tipoReporteCredito:'71RC',
    catModuloCl:'70MO',
    catAvisosMoratorio:'72DM',
    tipoExtrajudicial:'74TE',
    licenciado:'75AC',
    catTipoCartera: '73EC',
    catFraccion: '76FI',
    catTipoComprobante:'77TC',
    tipoReporPolizas:'78TP',
    tipoSolicituds:'79TS',
    catExpedientes: '80TE',
    tipoDeuda:'81PI',
    tipoInstrumento:'82TI',
    formaAdquisicion:'83FA',
    tipoValor:'84IO',
    catEstatusNomina:'85EN',
    catMedioDisper:'86MD',
    catComisionNomina:'87CN'



}

export default categorias;