
//Declaracion de variables para los hijos de las categorias
export const generales = {

    empresaSucursal: '03ES',
    clasificacionCredito: '56CC',
    clasificacionBuroCred: '54CB',
    condicionPagoCred: '12CP',
    solicitudCredito: '009',
    principal: '01DP',
    estadoCivilCasado: '35CA',
    tipoRefeBeneficiario: '31BE',
    cveEstCliCan: '58CB',
    cveEstCliBaj: '58SB',
    claseMovBanco: '50MB',
    claseMovContable: '50CO',
    claseMovCaja: '50MC',
    origenMov: '51EL', //Origen de los Movimientos CORE
    solAprobada: '59AP',
    credVigente: '001',
    cveProvedorderecursos: "31VR",
    cvPropietarioreal: "31PR",
    cveBeneficiario: "31BE",
    cvePresentantelegal: "31RP",
    cveTerceros: '22DT',
    solRechazada: '59RA',
    personalidadF: '55PF',
    personalidadM: '55PM',
    datoGeneralSecc: '70DG',
    domicilioSecc: '70DO',
    perfilInfSecc: '70PF',
    perfilIngSecc: '70PI',
    perfilEmpSecc: '70PE',
    refeSecc: '70RF',
    digitaSecc: '70DI',
    financiamiento: '68FN',
    identificacionRC: '68IR',
    monitoreoRC: '68MR',
    estadisticosRC: '68ER',
    conyugue: '69CD',
    mismoDomicilio: '69MD',
    parientes: '69PR',
    extrajudicial1: '74EX',
    extrajudicial2: '74ET',
    extrajudicial3: '74EJ',
    extrajudicialAdi: '74EA',
    comprobanteDigital: '77DI',
    auxiliarCuenta: '80AC',
    polizasPeriodo: '78PP',
    polisafolios: '79PF',
    actofiscalizacion: '81AF',
    fiscalconfunsa: '82FC',
    devolucion: '83DE',
    compesacion: '84CO',
    credPagado: '002',
    clasificacionCredNuevo: '001',
    clasificacionRenovado: '002',
    clasificacionReestructura: '003',
    riesgoConcentracionCartera: '71CC',
    riesgoTipoCredito: '72TC',
    riesgoPorZona: '73CZ',
    riesgoPorActividad: '74CA',
    matrizTransaccion: '75MT',
    expClientes: '80CS',
    expHipoteca: '80HA',
    expPrendaria: '80PA',
    expGarantLiquida: '80GL',
    expAval: '80AL',
    expGrupo: '80GC',
    expInversion: '80IN',
    cveAltaNomina: '85AL',
    cveEmpleadora: '01EE',
    cveNAplica: '01AP',
    cveAPorcentaje: '02AP',
    cveARango: '03AP',
    cveATantos: '04AP',
    cveDesempleo: '23DS',

    cveEstatusBEAC: '90AC',
    cveEstatusBEIA: '90IA',
    cveEstatusBEBJ: '90BJ',
    cveEstatusBEBQ: '90BQ'
}

export default generales;